# Generated by Django 4.0.2 on 2022-03-23 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_user_address_user_age_user_fname_user_lname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docname', models.CharField(max_length=30)),
                ('specialization', models.CharField(max_length=30)),
                ('docFees', models.DecimalField(decimal_places=2, max_digits=10)),
                ('docmobile', models.CharField(max_length=30)),
                ('docemail', models.EmailField(max_length=254, unique=True)),
                ('docpassword', models.CharField(max_length=30)),
            ],
        ),
    ]
