# Generated by Django 4.0.2 on 2022-03-23 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_doctor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='docFees',
            new_name='docfees',
        ),
    ]
