# Generated by Django 4.0.2 on 2022-03-25 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_docfees_doctor_docfees'),
    ]

    operations = [
        migrations.DeleteModel(
            name='doctor',
        ),
    ]
