# Generated by Django 4.0.2 on 2022-04-05 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='fees',
            field=models.IntegerField(blank=True, default=99, null=True),
        ),
    ]
