# Generated by Django 4.0.2 on 2022-03-25 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docname', models.CharField(max_length=30)),
                ('specialization', models.CharField(max_length=30)),
                ('docfees', models.DecimalField(decimal_places=2, max_digits=10)),
                ('docmobile', models.CharField(max_length=30)),
                ('docemail', models.EmailField(max_length=254, unique=True)),
                ('docpassword', models.CharField(max_length=30)),
            ],
        ),
    ]
