# Generated by Django 4.0.2 on 2022-03-26 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Doctor',
            new_name='Doctors',
        ),
    ]
