# Generated by Django 4.0.2 on 2022-04-02 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0002_rename_doctor_doctors'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='doc_pic',
            field=models.FileField(default='doc.png', upload_to='profile'),
        ),
    ]
